### PR TITLE
New xcode image plus bundler

### PR DESCRIPTION
**Pull request by raphaelcruzeiro**

### CODE REVIEW

**Comment by raphaelcruzeiro** [comment]
@joaoffcosta @tiago-queiros @yojique

**Comment by mrstif** [comment]
💃

**Comment by igorescobar** [comment]
Is this real life?

**Comment by raphaelcruzeiro** [comment]
Is it just fantasy?

**Comment by raphaelcruzeiro** [comment]
BTW, @joaoffcosta I believe that only I can publish this to Cocoapods. We need to transfer the publish rights to you.

**Pull request merged**
